"""initial schema

Revision ID: 278782a3e79c
Revises: 
Create Date: 2026-05-16 17:49:42.319325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278782a3e79c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_token_token_hash'), ['token_hash'], unique=True)

    op.create_table('relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_a_id', sa.Integer(), nullable=False),
    sa.Column('user_b_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', name='relationship_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('user_a_id < user_b_id', name='ck_relationship_user_order'),
    sa.ForeignKeyConstraint(['user_a_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a_id', 'user_b_id', name='uq_relationship_user_pair')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payer_user_id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'discarded', name='expense_status'), server_default='pending', nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('discarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discarded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=512), nullable=True),
    sa.Column('reverses_expense_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('confirmed_by_user_id IS NULL OR confirmed_by_user_id != created_by_user_id', name='ck_expense_no_self_confirm'),
    sa.CheckConstraint('total_cents > 0', name='ck_expense_total_positive'),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['discarded_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payer_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationship.id'], ),
    sa.ForeignKeyConstraint(['reverses_expense_id'], ['expense.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'discarded', name='payment_status'), server_default='pending', nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('discarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discarded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=512), nullable=True),
    sa.Column('reverses_payment_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('amount_cents > 0', name='ck_payment_amount_positive'),
    sa.CheckConstraint('confirmed_by_user_id IS NULL OR confirmed_by_user_id != created_by_user_id', name='ck_payment_no_self_confirm'),
    sa.CheckConstraint('from_user_id != to_user_id', name='ck_payment_distinct_parties'),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['discarded_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationship.id'], ),
    sa.ForeignKeyConstraint(['reverses_payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name='ck_expense_share_amount_positive'),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_id', 'user_id', name='uq_expense_share_expense_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_share')
    op.drop_table('payment')
    op.drop_table('expense')
    op.drop_table('relationship')
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_token_token_hash'))

    op.drop_table('auth_token')
    op.drop_table('user')
    # ### end Alembic commands ###
